FILE_NAME = "Contact"
VALUES_TO_BE_REPLACED_BY_NULL = ["unassigned", "N/A", " ", "", "nan"]
PARENT_KEY_FILED = "ID"
CHILD_KEY_FIELD = "ID__C"
COLOUM_NAME_WHERE_RECORD_SOURCE_TO_BE_STORED = "LEGACY__C"
